### ISSUE TITLE
XD7Controller GET and SET functions fail when used with psdscrunascredential

### ISSUE THREAD

**Issue by matt6697** [VirtualEngine/XenDesktop7#12]
XD7Controller GET and SET functions fail when used with **psdscrunascredential** Poweshell 5.0 parameter instead of **credential** Powershell 4.0 parameter.

After further investigations, the issue seems to be linked to the following code block at the end of both functions. The issue disapears when the code block is commented out.
```
## Overwrite the local ComputerName returned by AddInvokeScriptBlockCredentials
$invokeCommandParams['ComputerName'] = $ExistingControllerName;
```
I understand this code block as a way to run the powershell ScriptBlock on the **remote** `$ExistingControllerName` delivery controller.

Why is such a behavior needed in this XD7Controller function ?
Could we safely remove this code block to make the function compatible with Powershell 5 psdscrunascredential method ?

**Comment by matt6697** [comment]
I think that merging PR #8 could fix this issue.

**Comment by iainbrighton** [comment]
@matt6697 Getting any Citrix cmdlets to run on v4 requires initiating a remote connection to the local or a remote machine. They __have to run under a domain context__, but don't natively support specifying a `-Credential` parameter - hence the "hacks" 😭.

**Comment by iainbrighton** [comment]
@matt6697 I have pushed v2.5.9 to the PowerShell Gallery with this fix in it. Can you confirm it's resolved?

**Comment by matt6697** [comment]
I confirm it's resolved

**Comment by iainbrighton** [comment]
Thanks again for your help 😄
