### ISSUE TITLE
XD7DesktopGroup - Import-Module "no valid  module file was found in any module directory."

### ISSUE THREAD

**Issue by MattLDN** [VirtualEngine/XenDesktop7#15]
Hi 

In the XD7DesktopGroup  DSC Resource in version 2.5.10 there on line 305 there is an explicit module path listed:

Import-Module "$env:ProgramFiles\WindowsPowerShell\Modules\XenDesktop7\DSCResources\VE_XD7Common\VE_XD7Common.psd1" -Verbose:$false;

This causes DSC to fail when you have imported the module via the LCM from a remote location because the module path is proceeded by the version of the module,  e.g  Import-Module "$env:ProgramFiles\WindowsPowerShell\Modules\XenDesktop7\**2.5.10**\DSCResources\VE_XD7Common\VE_XD7Common.psd1" -Verbose:$false;  and so therefore the path that is targeted does not exist.  

It also looks like this is actually redundant as the module is already imported (at the end of the file)

"## Import the XD7Common library functions
$moduleParent = Split-Path -Path $moduleRoot -Parent;
Import-Module (Join-Path -Path $moduleParent -ChildPath 'VE_XD7Common');

Export-ModuleMember -Function *-TargetResource;"

If I simply remove the "Import-Module "$env:ProgramFiles\WindowsPowerShell\Modules\XenDesktop7\DSCResources\VE_XD7Common\VE_XD7Common.psd1" -Verbose:$false;
" section from the script, it completes without errors. 

Also, thanks for creating this Resource, it's great! 

Cheers
Matt

**Comment by iainbrighton** [comment]
@MattLDN I guess you're not specifying the `Credential` parameter? If you were then a PSRemoting session is used and then the module would not be imported 😢.

I need to find another way to import the module within the script block...

**Comment by iainbrighton** [comment]
@MattLDN Good catch! This is a PowerShell v5 (and later) thing.

Can you try changing the `Import-Module "$env:ProgramFiles\WindowsPowerShell\Modules\XenDesktop7\DSCResources\VE_XD7Common\VE_XD7Common.psd1" -Verbose:$false;` line 305 to
```powershell
$dscResourcesRoot = Split-Path -Path (Split-Path -Path $MyInvocation.MyCommand.Module.Path -Parent) -Parent;
$xd7CommonPath = Join-Path -Path $dscResourcesRoot -ChildPath 'VE_XD7Common\VE_XD7Common.psd1';
Import-Module $xd7CommonPath -Verbose:$false;
```
If you can confirm that works, I'll ensure that all other references are updated. Thanks 😄.

**Comment by MattLDN** [comment]
Hey Iain, 

If it still needs to be in script block,  why not just use Import-Module VE_XD7Common - don't define the path to the module. 

You don't need to explicitly define the part of the module,  it will look in the Modules Path (ProgramFiles\WindowsPowerShell\Modules\ & ProgramFiles x86\WindowsPowerShell\Modules\ ) for a folder with that name.. 

Or am I missing something?

**Comment by iainbrighton** [comment]
That's the problem. Try running `Get-Module -Name VE* -ListAvailable` and you won't see the VE_XDCommon module listed/discoverable. Unfortunately, `C:\Program Files\WindowsPowerShell\Modules\XenDesktop7\DscResources\VE_XDCommon` is not in the PSModulePath :sob:.

**Comment by MattLDN** [comment]
Oh right,  I see.  and Import-Module XenDesktop7 - doesn't pick up those functions?

**Comment by cwegener** [comment]
> If you can confirm that works, I'll ensure that all other references are updated. Thanks .

Just jumping in. I've been wanting to tackle this issue for a while now as well.

I'm not using the 'Credential' parameter either.

I have tested the Split-Path / Join-Path code and unfortunately it doesn't work when running `Start-DscConfiguration`

Following are the errors:

```
Cannot bind argument to parameter 'Path' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
    + PSComputerName        : localhost

Cannot bind argument to parameter 'Path' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
    + PSComputerName        : localhost

Cannot bind argument to parameter 'Name' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportModuleCommand
    + PSComputerName        : localhost
```

**Comment by cwegener** [comment]
@iainbrighton 

This one works for me. :smile:

The `$MyInvocation` syntax in your suggested code wasn't working.

Removing the `Module` property from the `$MyInvocation.MyCommand` works for me.

```powershell
$dscResourcesRoot = Split-Path -Path (Split-Path -Path $MyInvocation.MyCommand.Path -Parent) -Parent;
$xd7CommonPath = Join-Path -Path $dscResourcesRoot -ChildPath 'VE_XD7Common\VE_XD7Common.psd1';
Import-Module $xd7CommonPath -Verbose:$false;
```

**Comment by iainbrighton** [comment]
@MattLDN @cwegener v2.6.0 has been pushed the PowerShell Gallery and will hopefully resolve this issue. Please reopen the issue if it doesn't. Thanks for reporting 😃.

**Comment by cwegener** [comment]
@iainbrighton Just tested v2.6.0 with a 'localhost' node config and all three affected resources are now working fine when running the 'Set-TargetResource' functions that effect the changes.
