### ISSUE TITLE
XD7DesktopGroupApplication not working on recent XAXD/VAD releases

### ISSUE THREAD

**Issue by cwegener** [VirtualEngine/XenDesktop7#18]
When trying to use `XD7DesktopGroupApplication` DSC resource, the DSC resource
fails with an error due to *Citrix.Common.Commands* being a PSModule and not a
PSSnapin. But *XD7DesktopGroupApplication.psm1* is trying to load a PSSnapin by
the name of *Citrix.Common.Commands*

Error message when trying to use `XD7DesktopGroupApplication`:

    No Windows PowerShell snap-ins matching the pattern
    'Citrix.Common.Commands' were found. Check the pattern and then try the
    command again. PowerShell DSC resource VE_XD7DesktopGroupApplication
    failed to execute Set-TargetResource functionality with error message:
    Citrix XenDesktop 7.x Powershell SDK/Snap-in was not found.

**Comment by iainbrighton** [comment]
OH 😢. Do you know in what version this changed? I'm glad that Citrix are finally moving to modules, but I'll have to get this fixed..

**Comment by cwegener** [comment]
I will check how far I can go back in my XAXD ISO images. ISO images in my lab only go back to 7.11. I'll spin up 7.11 real quick and see what the situation is there.

**Comment by cwegener** [comment]
Alright. In 7.11, `Citrix.Common.Commands` is still a PSSnapin.

Let me check 7.13 next.

**Comment by cwegener** [comment]
Today must have been my lucky day. Ran two tests. One on 7.11 and one on 7.13

`Citrix.Common.Commands` is a PSSnapin in 7.11 and its a Module in 7.13

The question now is how a version check when loading `Citrix.Common.Commands`
should actually work, considering you have the whole Remoting Session support,
which means that the DSC node might not be the machine where the
`Citrix.Common.Commands` module is installed.

I personally have never used the Remoting stuff in XenDesktop7 DSC. I've only
ever used the XenDesktop7 DSC with WMF5 or higher and have always relied on the
built-in PSDSCRunAsCredentials together with a higher level orchestrator
(Ansible) to call the DSC resources across multiple nodes in the correct order.

Curious to hear what your thoughts are about handling this
`Citrix.Common.Commands` situation.

**Comment by iainbrighton** [comment]
@cwegener v2.6.0 has been pushed the PowerShell Gallery and will hopefully resolve this issue. Please reopen the issue if it doesn't.
