### ISSUE TITLE
XD7DesktopGroup add Desktops

### ISSUE THREAD

**Issue by meerkampdvv** [VirtualEngine/XenDesktop7#20]
There seems to be no way to add Desktops to the DesktopGroup like XD7DesktopGroupApplication but for Desktops.

Or am i Missing something ?

**Comment by iainbrighton** [comment]
Hi @meerkampdvv I think you need to use the [XD7DesktopGroupMember](https://github.com/VirtualEngine/XenDesktop7#xd7desktopgroupmember) resource?

**Comment by meerkampdvv** [comment]
i added a Machine (installed DesktopVDA role) with XD7DesktopGroupMember to a DesktopGroup.
(also to a Maschine Catalog)

but how do i publish its desktop? as XD7DesktopGroupApplication is only for aplications.

**Comment by iainbrighton** [comment]
Published desktops are there automatically, you just need to add an entitlement. See the example here: https://github.com/VirtualEngine/XenDesktop7#xd7entitlementpolicy
