### ISSUE TITLE
Get-AutomationPSCredential for Credential in Azure Automation

### ISSUE THREAD

**Issue by bdawg20000** [VirtualEngine/XenDesktop7#23]
When trying to supply a credential for the resources using this:

`$CitrixAdmin = Get-AutomationPSCredential -Name 'CtxSvcAccount'`

```
	XD7Site XD7Site {
		SiteName = $CitrixSiteName
		DatabaseServer = $DatabaseServer
		SiteDatabaseName = $SiteDatabaseName
		LoggingDatabaseName = $LoggingDatabaseName
		MonitorDatabaseName = $MonitorDatabaseName
		Credential = [PSCredential]$CitrixAdmin
		DependsOn = '[XD7Feature]XD7Controller','[XD7Database]XD7SiteDatabase','[XD7Database]XD7SiteLoggingDatabase','[XD7Database]XD7SiteMonitorDatabase'
	}
```
I get an error when trying to compile in Azure Automation

> System.InvalidOperationException error processing property 'Credential' OF TYPE 'XD7Database': Converting and storing encrypted passwords as plain text is not recommended. For more information on securing credentials in MOF file, please refer to MSDN blog: http://go.microsoft.com/fwlink/?LinkId=393729 At line:110 char:2 + XD7Database

Any ideas as to why this resource would support being compiled in Azure Automation?

**Comment by cwegener** [comment]
@bdawg20000: It would appear that you are talking about the usual PowerShell
DSC credential management. When compiling PowerShell DSC configurations into
MOF, the MOF files will store plain-text credentials. This feature is of course
disabled by default in PowerShell DSC and you would need to tell PowerShell DSC
explicitely that you want it to allow the storing of plain-text credentials in
the MOF files.

I have no idea how Azure impacts this.
