### ISSUE TITLE
StoreFront resources are limited to only one Farm per Store

### ISSUE THREAD

**Issue by cwegener** [VirtualEngine/XenDesktop7#24]
The new StoreFront resources seem to implement a particular design that
enforces a 1-to-1 relationship between StoreFront stores and the associated
farm(s) of a store. It does not appear to be possible to configure more than
one farm per StoreFront store.

The underlying PowerShell module ('Citrix.StoreFront') does not have this
limitation.

Also, the 'XD7StoreFrontStore' resource aggregates a total of *three* different
entities from the undelying PowerShell module ('StoreService',
'AuthenticationService', 'StoreFarm') into one single DSC configuration entity.

Such aggregation appears to break from the other (older) resources where each
XD7 DSC resource maps nicely to one single underlying PowerShell module entity,
which makes working with the DSC resources seamless.

Is there any particular reason that the StoreFront DSC resources break with
this previous pattern?

**Comment by BrianMcLain** [comment]
This was just due to the requirements I was given for how to configure a store. I'm working on getting a pull request now to fix these issues.

**Comment by iainbrighton** [comment]
@BrianMcLain Does PR #26 resolve this issue (it's not entirely clear)?

**Comment by BrianMcLain** [comment]
Yes.  This should be resolved.  The XD7StoreFrontStore is still the same (was only clear way to set up the first one with all the requirements).  If you want to add more, you can use the 
XD7StoreFrontStoreFarm to add an additional farm.

**Comment by iainbrighton** [comment]
@cwegener @BrianMcLain I have a basic `Store` resource that only creates the store permitting farms to be added and managed via the `XD7StoreFrontStoreFarm` resource. I'll get this pushed so you can have a look and we can discuss the best way forward...

**Comment by iainbrighton** [comment]
@BrianMcLain I agree with @cwegener in thinking that the current `XD7StoreFrontStore` implementation is doing too much. Even in the codebase, there are comments on things that don't work or still need to be implemented.

I have created a simpler [XD7StoreFrontStoreBase](https://github.com/VirtualEngine/XenDesktop7#xd7storefrontstorebase) resource, but now we need to decide what to do with it and the existing `XD7StoreFrontStore` resource. Here are two valid options:

1. Replace the existing `XD7StoreFrontStore` resource with a (complicated) composite resource. This maintains backward compatibility, delegating the configuration to the underlying `XD7StoreFrontAuthenticationService`, `XD7StoreFrontStoreBase` and `XD7StoreFrontStoreFarm` resources.
2. Replace the existing `XD7StoreFrontStore` resource with the `XD7StoreFrontStoreBase` implementation. __This is cleaner but is a breaking change in the XD7StoreFrontStore resource and, whilst it's my preference, it might impact a large number of users__

Any preferences or ideas?
Thanks, Iain

**Comment by iainbrighton** [comment]
Here is a working [composite resource](https://gist.github.com/iainbrighton/2479239caf5b917ccf3cf49e802b5646) example

**Comment by BrianMcLain** [comment]
I’ll discuss with my team here.  I would also prefer to do it the cleaner way.  We don’t have any of this in production yet, so it wouldn’t be a huge issue for us to change.

**Comment by BrianMcLain** [comment]
@iainbrighton Let's go ahead and go with your option 2.  We agree that's the best option and wouldn't require much of a change to our configs.

**Comment by cwegener** [comment]
Thanks guys. Sounds like a good plan. I'm happy with that. Once
released, I can decommission my own internally managed closed-source
StoreFront DSC resource and migrate to XenDesktop7 for StoreFront
management! :)

**Comment by BrianMcLain** [comment]
@cwegener - can you validate if you think this has been resolved with the latest release?  Sorry, I just realized I was looking at this wrong.  It's still just in DEV branch.

**Comment by rubenribeiro** [comment]
Any plan to move this into the master branch?

**Comment by iainbrighton** [comment]
Done! v2.9.0 is now in the PS Gallery 😃.
