### ISSUE TITLE
XD7StoreFrontRegisterStoreGateway configures authentication service protocols

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/XenDesktop7#38]
Similar to #24, the `XD7StoreFrontRegisterStoreGateway` resource configures a Storefront Store's authentication methods, enabling conflicting configurations. For example, the following configuration will never converge as the Store's authentication methods will be disabled and enabled on each pass:
```powershell
Configuration ConflictingAuthenticationProtocols {
    Import-DscResource -ModuleName XenDesktop7

    XD7StoreFrontRegisterStoreGateway Gateway1 {
        GatewayName = 'Netscaler1'
        StoreName = 'Store'
        AuthenticationProtocol = @('ExplicitForms','IntegratedWindows')
        EnableRemoteAccess = $True
        Ensure = 'Present'
    }

    XD7StoreFrontRegisterStoreGateway Gateway2 {
        GatewayName = 'Netscaler2'
        StoreName = 'Store'
        AuthenticationProtocol = @('CitrixAGBasic','CitrixFederation')
        EnableRemoteAccess = $True
        Ensure = 'Present'
    }
}
```
Enabling and disabling of a Store's authentication methods should be left to the `XD7StoreFrontAuthenticationServiceProtocol` resource.

**Comment by BrianMcLain** [comment]
@iainbrighton how do you want to handle these storefront updates? I'm fine with making the updates, just don't want to work on the ones if you are already working on them.  Can you assign them to me if you aren't going to address them yourself?

**Comment by iainbrighton** [comment]
@BrianMcLain I have no updates to push at present, so feel free to work on any of them - just assign yourself to the issue so people know your working on it 😉!

**Comment by BrianMcLain** [comment]
Either I don't know what I'm doing, or I don't have permissions to assign it to myself.

**Comment by iainbrighton** [comment]
Hmmm - it would have thought you'd be able to do that, it appears not 😢. I have assigned this issue to you and if you'd like to be assigned any other issue, just add a comment to the issue! Thx

**Comment by BrianMcLain** [comment]
Should this be closed now?
