### ISSUE TITLE
XD7Database not populating DependsOn

### ISSUE THREAD

**Issue by alexaymonier** [VirtualEngine/XenDesktop7#4]
Hi Iain,

Just started playing DSC and these (beautifully written) resources. So far i have used the following resources to test this out: 
File - to copy a zip over of the XD7 media top the test server
Archive - to then unzip the media
XD7Feature -  to install the controller roll
XD7Database - to set up the XD7database
I have noticed a oddity or two with the XD7Database resource.
1. When adding depends on, i am not able to enumerate any other resources but can manually type the resource i am wanting to depend on.
2. If i run the following resources in depends on order File, Archive then XD7Feature -  this works perfectly fine. However if i then run File, Archive, XD7Feature then XD7Database then dsc starts to error out complaining (The PowerShell DSC resource MSFT_ArchiveResource from module <PSDesiredStateConfiguration,1.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC resource.) IF i remove XD7Database  then it works fine again. As a work around i can edit the MOF and set the archive resource to 1.1 then it works fine.

Please let me know if you need any more info. 

Thanks
Alex

**Comment by iainbrighton** [comment]
Hi Alex,

Glad you find them useful!

I think you may be suffering from the “DSC resource dependencies cannot contain a number” bug/feature. What versions of OS/WMF are you a) generating the MOF files on and what version(s) are on the target nodes?

Thanks, Iain

**Comment by alexaymonier** [comment]
Hi Iain,

Thanks for the quick reply. I am running WMF 5 RTM on Server 2012R2 for both the authoring server and the XDController. This also happened with WMF5 prod preview.

Thanks
Alex

**Comment by alexaymonier** [comment]
Hi Ian,

Apologies, I have found out why the depends on was not populating. I have a node statement for the controllers to install that roll then I have a second node statement for the primary Controller which also is the database creator. The population of the depends on is restricted to that node statement block.

Ill take up the module version on powershell.org and see if anyone else is having that problem too.

Thanks for your time and have a great Christmas

Alex

**Comment by iainbrighton** [comment]
Hi Alex,

No problem.

The issue is on the target where the MOF is applied? Do you somehow have 2 versions of the Archive resource on the target that's been upgraded?

Have a great Christmas yourself :D

Iain
