### ISSUE TITLE
XD7AccessPolicy - Test fails when no previous policies exist

### ISSUE THREAD

**Issue by ktBonefish** [VirtualEngine/XenDesktop7#53]
https://github.com/VirtualEngine/XenDesktop7/blob/5fc439c01369665ceca3d046645414a8af5c8084/DSCResources/VE_XD7AccessPolicy/VE_XD7AccessPolicy.psm1#L188

When no previous Access Policy exists on the server, the comparison performed on line 188 returns the below error. This causes the test phase of DSC to fail and error out.
`Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.`

This is due to the $targetResource created on 177 having null fields in it when it's created on lines 72-83.  On line 70 when Get-BrokerAccessPolicyRule returns no results due to none being on the server previously the $targetResource hash table has $null values for various properties and causes the resulting comparison above to fail.

**Comment by iainbrighton** [comment]
@ktBonefish The change has been published to the PSGallery, but I have no way to confirm whether it's fixed.
