### ISSUE TITLE
XD7StoreFrontFarmConfiguration always non-compliant after consistency check

### ISSUE THREAD

**Issue by rooney-smith** [VirtualEngine/XenDesktop7#54]
The following DSC code will set the expected configuration but always returns "not in desired state" after a state check (e.g. Test-DSCConfiguration) is performed.

XD7StoreFrontFarmConfiguration SetSTFConfig
{
    StoreName = "Store"
    AdvancedHealthCheck = $true
}

When looking through the module code line 34 is
$null = Get-STFStoreFarm -StoreService $StoreService -Verbose -OutVariable Configuration

Get-STFStoreFarm does not return the Store configuration ! (or not that I can see). 
I think the cmdlet you should be using on line 34 is Get-STFStoreFarmConfiguration
![Get-STFStoreFarmConfiguration](https://user-images.githubusercontent.com/58815657/214147313-3668b5d1-e14e-4429-b737-d06edc372505.PNG)

**Comment by iainbrighton** [comment]
@rooney-smith The change has been published to the PSGallery, but I have no way to confirm whether it's fixed.
