### ISSUE TITLE
Optimal Gateway Routing Resource Farm Property problem

### ISSUE THREAD

**Issue by shaun-avenell** [VirtualEngine/XenDesktop7#55]
In Visual Code the ‘Farm’ property in configuration was showing error as not valid 
 
                    XD7StoreFrontOptimalGateway "AddOptimalGatewayRoute$Storenumber$OGRNumber"
                    {
                        
                            GatewayName = $OptimalGWRoute.OGRGatewayName
                            ResourcesVirtualPath = $StoreFrontConfig.VirtualPathRoot + $StoreName
                            Hostnames = $OptimalGWRoute.OGRHostnames
                            StaUrls = $OptimalGWRoute.OGRGatewayNameStaUrls
                            StasUseLoadBalancing = $OptimalGWRoute.OGRGatewayNameStasUseLoadBalancing
                            StasBypassDuration = $OptimalGWRoute.OGRGatewayNameStasBypassDuration
                            Zones = $OptimalGWRoute.OGRZones
                            Farms = $OptimalGWRoute.OGRFarms         ###This was flagged as invalid property
                            Ensure = 'Present'
                            DependsOn = "[XD7StoreFrontWebReceiverPluginAssistant]SFConfigRcvrPlugin$StoreNumber"
                    }
                }
 
The mof file “VE_XD7StoreFrontOptimalGateway.schema.mof”  from within the Xendesktop7 module, was showing the Farm parameter as Read Only, all others were Write.

I updated the file as below to switch Farms property from Read to Write , which then fixed the problem. This property is certainly writeable via the Citrix Powershell SDK so I think this is valid.

[ClassVersion("1.0.0.0"), FriendlyName("XD7StoreFrontOptimalGateway")]
class VE_XD7StoreFrontOptimalGateway : OMI_BaseResource
{
                [Key, Description("StoreFront gateway name")] String GatewayName;
                [Write, Description("Site Id")] UInt64 SiteId;
                [Required, Description("Resources Virtual Path")] String ResourcesVirtualPath;
                [Required, Description("Hostnames")] String Hostnames[];
                [Required, Description("Secure Ticket Authority server Urls")] String StaUrls[];
                [Write, Description("Load balance between the configured STA servers")] Boolean StasUseLoadBalancing;
                [Write, Description("Time before retrying a failed STA server")] String StasBypassDuration;
                [Write, Description("Enable session reliability")] Boolean EnableSessionReliability;
                [Write, Description("Request STA tickets from two STA servers")] Boolean UseTwoTickets;
                **[Write, Description("Farms")] String Farms[];                                                ##changed from Read to Write**
                [Write, Description("Zones")] String Zones[];
                [Write, Description("Enabled On Direct Access")] Boolean EnabledOnDirectAccess;
                [Write, Description("Ensure"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

**Comment by iainbrighton** [comment]
@shaun-avenell The change has been published to the PSGallery, but I have no way to confirm whether it's fixed.

**Comment by shaun-avenell** [comment]
Many thanks Ian, I have made the change locally and it does work.

Regards

Shaun
