### ISSUE TITLE
manifest contains one or more members that are not valid.

### ISSUE THREAD

**Issue by JCarballada** [VirtualEngine/XenDesktop7#6]
Hello,
AT the time to try to start-dsconfiguratoin I am getting this error message.
I am using Powershell 5.0 on Windows 2012 R2. 

mporting module VE_XD7Site failed with error - The 'C:\Program Files\WindowsPowerShell\Modules\XenDesktop7\2.3.1\DscResources\VE_XD7Site\VE_XD7Site.psd1' module cannot be imported because 
its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 
'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 
'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 
'CmdletsToExport', 'DscResourcesToExport', 'HelpInfoURI', 'RootModule', 'DefaultCommandPrefix'). Remove the members that are not valid ('CreatingXDSite', 'ResourcePropertyMismatch', 
'ResourceNotInDesiredState', 'InvokingScriptBlock', 'XenDesktopSDKNotFoundError', 'ResourceInDesiredState', 'InvokingScriptBlockWithParams'), then try to import the module again.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : SERVERXXXXX

Thanks,
Jacobo.

**Comment by iainbrighton** [comment]
Hi @jakobo82 - I'm not sure what's going on here. I did rename the resources files, but this _shouldn't_ cause DSC to attempt to load them as a module manifest as the MSFT resources use this format! I'm just spinning up a 2012 R2 box with PS v5 on to check it out.

**Comment by iainbrighton** [comment]
@jakobo82 I see the issue!

``` powershell
Importing module VE_XD7VDAFeature failed with error - The 'C:\Program Files\WindowsPowerShell\Modules\XenDesktop7\DscResource
s\VE_XD7VDAFeature\VE_XD7VDAFeature.psd1' module cannot be imported becauseits manifest contains one or more members that are not valid. The valid
manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author','CompanyName', 'Copyright', 'ModuleVersion', 'Description',
'PowerShellVersion', 'PowerShellHostName', 'PowerShellHostVersion','CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture',
'RequiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess','PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList',
'FunctionsToExport', 'VariablesToExport', 'AliasesToExport','CmdletsToExport', 'DscResourcesToExport', 'HelpInfoURI', 'RootModule',
'DefaultCommandPrefix'). Remove the members that are not valid('ProcessExited', 'UninstallingRole', 'ResourceInDesiredState',
'ProcessLaunched', 'InvalidSourcePathError', 'WaitingForProcessToExit','ResourceNotInDesiredState', 'InstallingRole', 'SourceDirectorySet',
'SecureBootEnabledError', 'StartingProcess', 'StartingProcessAs',
'NoValidSetupMediaError', 'LogDirectorySet'), then try to import the module again. LCM failed to start desired state configuration manually.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BootStrap.ps1
```

This was due to the resource files being named the same as the modules. I'm not entirely sure why the error wasn't picked up by the unit tests? Regardless, there's a new version v2.3.2 in the gallery that should hopefully resolve this issue for you. Can you test and let me know?

**Comment by iainbrighton** [comment]
@jakobo82 Can you confirm that the 2.3.2 version has resolved your issues? Thx
