### ISSUE TITLE
XD7StoreFrontRoamingGateway TEST Always Fails on Gateway with STAURL configured

### ISSUE THREAD

**Issue by shaun-avenell** [VirtualEngine/XenDesktop7#60]
**Symptom**
When running DSC compliance check against any gateway with STAs configured the status returned will always be failed.
The JSON detail from the compliance run shows :-
[[XD7StoreFrontRoamingGateway]AddSFNetScalerGW3] Property'SecureTicketAuthorityUrls' is NOT in desired state; 
expected 'https:// Server.NET/scripts/ctxsta.dll,https:// Server.NET/scripts/ctxsta.dll', 
actual 'https:// Server.NET/scripts/ctxsta.dll,**False**,,https:// Server.NET/scripts/ctxsta.dll,**False**,'."},

The reason for this is the return from the GET function in the Resource contains additional values not just the URLs, these additional values are then reused by the TEST function:-
PS C:\Windows\system32> (Get-STFRoamingGateway -Name GWName).SecureTicketAuthorityUrls

                         https://server.net/scripts/ctxsta.dll               	 False            
                         https://server.net/scripts/ctxsta.dll               	 False

**Solution**
Modifying the GET-TargetResource function to retrieve only the StaURL values resolves the failing compliance. The code was locally amended in the XD7StoreFrontRoamingGateway resource PSM1 of the XenDesktop7 DSC module which was then upload into Azure and the configuration recompiled. Following this the StaURL tests show as compliant in the Azure DSC console as expected
Adding **.StaUrl** ensures only the required values are returned:-
PS C:\Windows\system32> (Get-STFRoamingGateway -Name GWName).SecureTicketAuthorityUrls.StaUrl

Code change as follows to the “ReturnValue” section of the GET-TargetResource Function:-

      $returnValue = @{
                   Name = [System.String]$Gateway.Name
                   LogonType = [System.String]$Gateway.Logon
                   SmartCardFallbackLogonType = [System.String]$Gateway.SmartCardFallback
                   Version = [System.String]$Gateway.Version
                   GatewayUrl = [System.String]$Gateway.Location
                   CallbackUrl = [System.String]$Gateway.CallbackUrl
                   SessionReliability = [System.Boolean]$Gateway.SessionReliability
                   RequestTicketTwoSTAs = [System.Boolean]$Gateway.RequestTicketTwoStas
                   SubnetIPAddress = [System.String]$Gateway.IpAddress
         ##     SecureTicketAuthorityUrls [System.String[]]$Gateway.SecureTicketAuthorityUrls             ##modified from this
                  SecureTicketAuthorityUrls [System.String[]]$Gateway.SecureTicketAuthorityUrls.StaUrl   ##to this
                  StasUseLoadBalancing = [System.Boolean]$Gateway.StasUseLoadBalancing
                  StasBypassDuration = [System.String]$Gateway.StasBypassDuration
                  GslbUrl = [System.String]$Gateway.GslbLocation
         }
        $returnValue

**Comment by iainbrighton** [comment]
@shaun-avenell Thanks. I haven't been able to confirm that this has fixed the issue, but thought I'd better add it before the code signing certificate expires!

**Comment by iainbrighton** [comment]
Merged

**Comment by shaun-avenell** [comment]
Many thanks Ian.

Regards

Shaun
